version: '3.9'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  mobashi-surv-ui:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile
    env_file:
      - ./configs/node/localdev/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
      - type: bind
        source: ./local_vars/development/configs
        target: /workspaces/mobashi-surv-ui/mobashi-surv-ui/src/app/local_configs
        bind:
          create_host_path: true
        read_only: true
      - type: bind
        source: ./local_vars/development/assets
        target: /workspaces/mobashi-surv-ui/mobashi-surv-ui/src/assets/local_assets
        bind:
          create_host_path: true
        read_only: true

    # Overrides default command so things don't shut down after the process ends.
    # It seems to be ignored, though!!!
    command: /bin/sh -c "while sleep 1000; do :; done"
